### ISSUE TITLE
Config questions

### ISSUE THREAD

**Issue by hydra** [vespaman/Smoothieware-CHMT#3]
Hi @vespaman 

If it's not too much trouble, I'd like to quiz you about your config a little.

1) I notice you've got two sets of actuators for the peelers, LPEELER, LPEELER12, RPEELER, RPEELER12.  I notice the L/R PEELER have boolean 'off' commands which advance the feeder 6mm in the gcodedriver. However the L/RPeeler12 advance 14mm, so was just wondering what the '12' in the name was?

2) you have two actuators defined, called `Feed (Left side peel)` and `Feed (Right side peel)`, these use the rotation axis directly, which is probably what I should be using right, instead of the LPEELER/RPEELER which seems to be legacy way of doing it, however I notice in your gcode driver settings you have a boolean on/off command defined for the `Feed (Right side peel)` which seem to be drag-pin gcode commands I'm guessing this is a mistake?

![image](https://github.com/vespaman/Smoothieware-CHMT/assets/57075/8d23c86d-c4c6-4dee-9a70-c200262b7373)

https://github.com/vespaman/Smoothieware-CHMT/blob/481aaa8d3f128cc9b43f02e661041d2773a6d3aa/ConfigSamples/CHMT/vespamans_machine.xml#L3659-L3663

https://github.com/vespaman/Smoothieware-CHMT/blob/481aaa8d3f128cc9b43f02e661041d2773a6d3aa/ConfigSamples/CHMT/vespamans_machine.xml#L395-L407

As I have more questions, I'll post here, to keep things organized.

**Comment by vespaman** [comment]
Hi @hydra 

1. Yes, these are the old stuff. I probably kept it to be able to use the actuator panel to run the peelers. But honestly, they might just be forgotten. The '12' is the component in tape distance, and perhaps I wanted some extra mm on the peeler, just to be sure. It can happen that the peeler friction cannot overtake the tape cover glue on start of peel, so maybe that is why I let the peeler motors run a bit longer. But I don't remember if I used that setting much at all. Maybe best to remove, and/or rename. Certainly there's no need to have booth the 12 and the 4 actuators.
2. That is probably something left behind. I tried a lot of ways before I learned that I had to use profile value types. As you may have seen, it is quite easy to forget about settings in the actuator setup dialog, since you don't really have any overview, and have to use the drop down on each and every setting. After a while, when testing different stuff, brain get's a bit mushy. :)
